alter table dogs drop constraint dev_dogs_dog_owner_id_fkey;
alter table dogs drop constraint dev_dogs_dog_type_id_fkey;

alter table injection_certifications drop constraint dev_injection_certifications_dog_id_fkey;

alter table dogruns drop constraint dev_dogruns_dogrun_manager_id_fkey;

alter table regular_business_hours drop constraint dev_regular_business_hours_dogrun_id_fkey;

alter table special_business_hours drop constraint dev_special_business_hours_dogrun_id_fkey;

alter table dogrun_images drop constraint dev_dogrun_images_dogrun_id_fkey;

alter table dogrun_tags drop constraint dev_dogrun_tags_dogrun_id_fkey;
alter table dogrun_tags drop constraint dev_dogrun_tags_tag_id_fkey;

alter table auth_dog_owners drop constraint dev_auth_dog_owners_dog_owner_id_fkey;

alter table auth_dogrun_managers drop constraint dev_auth_dogrun_managers_dogrun_manager_id_fkey;